### ISSUE TITLE
PROPOSAL: make appending to current environment list the default

### ISSUE THREAD

**Issue by jpcoles** [eth-cscs/slurm-uenv-mount#35]
### Problem

Although we don't have this implemented yet, once we have our `uenv` command, one might expect that one can mount multiple images by running the command multiple times, e.g.:
```
$ uenv mount imageA
$ uenv mount imageB /user-tools
$ uenv list
imageA /user-environment
imageB /user-tools
```

The current implementation of the `--uenv` option overrides any currently mounted images. If a user has a default environment mounted, it is unexpected to lose it if they subsequently mount a tools environment (for example) when running a slurm job. 
```
$ uenv list
imageA /user-environment
$ srun --uenv=imageB:/user-tools /user-environment/bin/gcc
command not found: gcc
```

A similar problem occurs when using sbatch to set a uenv and then running srun with another uenv: the command executed by srun no longer has access to the uenv given to sbatch.

This may become especially problematic if we provide a default user environment that a user would expect to be always available.

One solution that works right now is to use the envvar that we have to keep track of mounted images:
`srun --uenv=$UENV_MOUNT_LIST,tools.sqfs:/user-tools findmnt /user-tools`

This has the disadvantages that 
1. our use of $UENV_MOUNT_LIST is exposed to the user which could change or disappear in the future,
2. the format of $UENV_MOUNT_LIST has to be consistent with the syntax that `--uenv` accepts,
3. the behaviour is unexpected given how the `uenv` command may work,
4. there is extra noise every time a user wants to add to the default environment.

### Proposal

1. Make the default action of `--uenv` be to extend the current list of images.
2. Add `--uenv-clear` which would effectively set $UENV_MOUNT_LIST to "" before adding any images (potentially) listed in `--uenv`. 

### Reasoning

1. The user is forced to explicitly state that they wish to clear the environment and load a completely new set.
2. `--uenv` behaves more list `uenv`
3. We are more flexible in deciding how to propagate/track our list of mounted images.

### Potential Issues

1. User may attempt (inadvertently) to mount duplicate images to the same or different mount point
2. Do we complicate the case where a user wants to run commands from different user environments mounted on /user-environment. In this case the syntax would be:
```
srun --uenv-clear --uenv=... command
srun --uenv-clear --uenv=... command
```

**Comment by simonpintarelli** [comment]
I agree, that when multiple images can be mounted, the user could expect that `uenv mount ..` can be called repeatedly, each time appending to or overriding already mounted images.

In the current implementation (setuid squashfs-mount and slurm plugin), `prctl(PR_SET_NO_NEW_PRIVS, 1, 0, 0, 0)` is called in the end. This prevents child processes from gaining new privileges. It also prevents `squashfs-mount` to be called recursively. Commenting that line might be a potential security issue. 

We first need to figure out if `PR_SET_NO_NEW_PRIVS` can be safely removed or not.

**Comment by bcumming** [comment]
The limitation that we can make successive calls to `uenv start` is, as @simonpintarelli points out, a technical limitation of the current implementation.
However it also reflects a concious design decision: the user environments are designed so that one environment canbe started at a time.
That is, the running environment has to be stopped before a new environment can be started.

The original design was that all environments could be mounted at `/user-environment`, which was extended to support multiple (image,mount) pairs to support the specific workflow of side-loading tools.
The only workflow where mounting an additional image would make sense with two mount points like this, would be if a user wanted to load additional tools after starting an image.

For the `uenv` command line utility, I have been thinking about an interface like the following:

```bash
# start the gromacs 2019 environment
uenv start gromacs.2019
uenv run gromacs.2019 --view=default srun -n4 -N1 gmx <args>

# start the gromacs 2019 environment with a "profiler" tools
uenv start gromacs.2019 --tools=profilers
uenv run gromacs.2019 --tools=profilers --view=default srun -n4 -N1 profile gmx <args>
```

Where the user doesn't provide the mount point - the tool automatically mountes everything at `/user-environment`.
To load tools, instead of providing a `/tools` mount point, a CLI flag `--tools` would always mount tools at `/tools`.
