### ISSUE TITLE
Change flag names

### ISSUE THREAD

**Issue by jpcoles** [eth-cscs/slurm-uenv-mount#9]
Change the accepted file and mount point flags to --uenv-file and --uenv-path. We can discuss the name of the path flag, but using --uenv-mount a) sounds like a command and b) "mount" is technical jargon that not every user would be familiar with. While path can also be considered jargon, it is probably more widely understood.

**Comment by bcumming** [comment]
My two cents: `--uenv-mount` vs. `--uenv-path`, the difference is probably not that important.
I would lean towards using the `mount` because:
- it is the more specific and correct term that will cause less confusion for users who know what a mount is. That said, the man page for `mount` uses both `mountpoint` and `dir` in similar contexts.
- mount is used by docker

After a phone call and judicious use of a random number generator, we settled on `--uenv-mount`

**Comment by bcumming** [comment]
This was addressed in #4.
